let slider = tns({
    container: '.hero__slider',
    items: 1,
    slideBy: 'page',
    // autoWidth: true,
    center: true,
    mouseDrag: false,
    // arrowKeys: true,
    // autoplay: false,
    loop: true,
    // fixedWidth: 1440,
    controls: true,
    controlsContainer: '#customize-controls',
    // prevButton: '.prev',
    // nextButton: '.next',
    nav: false,
    navPosition: 'bottom',
    // swipeAngle: false,
    speed: 400,
    // viewportMax:1440
});
